import { CursorCanvas } from "@/components/CursorCanvas";
import { ScrollSmootherProvider } from "@/components/ScrollSmootherProvider";
import type { Metadata } from "next";
import "./globals.css";
import { SsgoiProvider } from "./ssgoi-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <CursorCanvas />
        <ScrollSmootherProvider>
          <SsgoiProvider>{children}</SsgoiProvider>
        </ScrollSmootherProvider>
      </body>
    </html>
  );
}
